import { createSlice } from "@reduxjs/toolkit";

// Define a slice of the Redux state for managing UI-related data
const uiSlice = createSlice({
  name: "ui", // Name of the slice
  initialState: { cartIsVisible: false, notification: null }, // Initial state of the slice
  reducers: {
    // Define reducer functions to handle state updates
    toggle(state) {
      // Reducer function to toggle the cart visibility
      state.cartIsVisible = !state.cartIsVisible; // Toggle the cartIsVisible boolean
    },
    showNotification(state, action) {
      // Reducer function to show a notification
      state.notification = {
        // Update the notification object with the payload data
        status: action.payload.status, // Notification status (e.g., "success", "error")
        title: action.payload.title, // Notification title
        message: action.payload.message, // Notification message
      };
    },
  },
});

// Export the action creators generated by createSlice
export const uiActions = uiSlice.actions;

// Export the reducer function generated by createSlice
export default uiSlice;
